apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-dr-demo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/SarraMehrez/gitops-dr-demo-app"
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true